---
title: "git_01"
author: "Nathaly Ruiz"
date: "2024 Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

HE shouts amain, he shouts again,

(Her brother, fierce, as bluff King Hal),

"I tell you flat, I shall do that!"

She softly whispers " 'May' for 'shall'!"

He wistful sighed one eventide
 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,

Some say in ice.

From what I've tasted of desire

I hold with those who favor fire.

But if it had to perish twice,


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

<<<<<<< HEAD
=======
The sun was shining on the sea,

Shining with all his might:

He did his very best to make

The billows smooth and bright--

And this was odd, because it was

The middle of the night.


The moon was shining sulkily,

Because she thought the sun

Had got no business to be there

After the day was done--

"It's very rude of him," she said,

"To come and spoil the fun!"
>>>>>>> verse3


## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

In a cupboard small, beneath the stair,

Lived a boy with messy, untamed hair.

He knew not magic, nor of his fame,

Till Hogwarts sent a letter in his name.

A wand of holly, a scar like a flash,

Marking the day of a dark night’s clash.

With Ron and Hermione by his side,

Into the wizarding world, he'd stride.

Through halls of stone, and spells that sing,

He’d face the Dark Lord, rise as a king.

The Sorting Hat, it chose his fate,

In Gryffindor's warmth, his heart would wait.

Quidditch games and broomsticks high,

Flying fast across the sky.

A hidden chamber, a serpent's bite,

He faced the dark but held the light.

In shadows deep, and darkened hall,

He sought the truth, he’d give his all.

Dementors cold, and fires that gleam,

Through every year, a haunting dream.

Prophecies whispered, and secrets spun,

He was the boy who would never run.

Through trials fierce, through loss and pain,

In the end, the light would reign.

Voldemort’s fall, the wand of might,

The world reclaimed, set things right.

The Boy Who Lived, with courage true,

His story ends, but magic grew.

